//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcms.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment.
        /// </summary>
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signature.
        /// </summary>
        internal static string AddSignature {
            get {
                return ResourceManager.GetString("AddSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERT!.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        internal static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string Approvedby {
            get {
                return ResourceManager.GetString("Approvedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By :.
        /// </summary>
        internal static string Approvedby_ {
            get {
                return ResourceManager.GetString("Approvedby:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By - Comments : .
        /// </summary>
        internal static string ApprovedComment {
            get {
                return ResourceManager.GetString("ApprovedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        internal static string Approveddate {
            get {
                return ResourceManager.GetString("Approveddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date : .
        /// </summary>
        internal static string Approveddate_ {
            get {
                return ResourceManager.GetString("Approveddate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string ApprovedWorkorder {
            get {
                return ResourceManager.GetString("ApprovedWorkorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset : .
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Condition.
        /// </summary>
        internal static string AssetCondition {
            get {
                return ResourceManager.GetString("AssetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment : .
        /// </summary>
        internal static string Attachment_ {
            get {
                return ResourceManager.GetString("Attachment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Details.
        /// </summary>
        internal static string AttachmentDetail {
            get {
                return ResourceManager.GetString("AttachmentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Form.
        /// </summary>
        internal static string AttachmentForm {
            get {
                return ResourceManager.GetString("AttachmentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Name.
        /// </summary>
        internal static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit No.
        /// </summary>
        internal static string AuditNo {
            get {
                return ResourceManager.GetString("AuditNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Person :.
        /// </summary>
        internal static string AuthorizedPerson {
            get {
                return ResourceManager.GetString("AuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Draft : .
        /// </summary>
        internal static string BankDraft {
            get {
                return ResourceManager.GetString("BankDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Guarantee : .
        /// </summary>
        internal static string BankGuarantee {
            get {
                return ResourceManager.GetString("BankGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Area : .
        /// </summary>
        internal static string Businessarea {
            get {
                return ResourceManager.GetString("Businessarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Picture.
        /// </summary>
        internal static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change SQA Status.
        /// </summary>
        internal static string ChangeSQAStatus {
            get {
                return ResourceManager.GetString("ChangeSQAStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        internal static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Form .
        /// </summary>
        internal static string ChecklistForm {
            get {
                return ResourceManager.GetString("ChecklistForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist Type.
        /// </summary>
        internal static string ChecklistType {
            get {
                return ResourceManager.GetString("ChecklistType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Work Order.
        /// </summary>
        internal static string ChildWorkorders {
            get {
                return ResourceManager.GetString("ChildWorkorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Download.
        /// </summary>
        internal static string ClicktoDownload {
            get {
                return ResourceManager.GetString("ClicktoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Department.
        /// </summary>
        internal static string CompanyDepartment {
            get {
                return ResourceManager.GetString("CompanyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competent Person :.
        /// </summary>
        internal static string CompetentPerson {
            get {
                return ResourceManager.GetString("CompetentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURATION.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Name.
        /// </summary>
        internal static string ContractorName {
            get {
                return ResourceManager.GetString("ContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Note.
        /// </summary>
        internal static string Correctionnote {
            get {
                return ResourceManager.GetString("Correctionnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        internal static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string Createddate {
            get {
                return ResourceManager.GetString("Createddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Lookup.
        /// </summary>
        internal static string DataLookup {
            get {
                return ResourceManager.GetString("DataLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Description : .
        /// </summary>
        internal static string DefectDescription_ {
            get {
                return ResourceManager.GetString("DefectDescription:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Recified Date : .
        /// </summary>
        internal static string DefectRecifiedDate_ {
            get {
                return ResourceManager.GetString("DefectRecifiedDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature.
        /// </summary>
        internal static string DigitalSignature {
            get {
                return ResourceManager.GetString("DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery :.
        /// </summary>
        internal static string Discovery {
            get {
                return ResourceManager.GetString("Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Attachment.
        /// </summary>
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Master Data.
        /// </summary>
        internal static string DownloadMaster {
            get {
                return ResourceManager.GetString("DownloadMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Reading.
        /// </summary>
        internal static string EnterNewReading {
            get {
                return ResourceManager.GetString("EnterNewReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail ?.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        internal static string Filterby {
            get {
                return ResourceManager.GetString("Filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are entering into a secured area! Your IP, Login Time, Username have been noted and send to the server administrator! This service is restricted to authorized users only..
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any enquiries regarding your account, please call the respective hotline below..
        /// </summary>
        internal static string ForanyenquirieS {
            get {
                return ResourceManager.GetString("ForanyenquirieS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get GPS.
        /// </summary>
        internal static string GetGPS {
            get {
                return ResourceManager.GetString("GetGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Coordinate.
        /// </summary>
        internal static string GPSCoordinate {
            get {
                return ResourceManager.GetString("GPSCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Coordinate (NEW).
        /// </summary>
        internal static string GPSCoordinateNew {
            get {
                return ResourceManager.GetString("GPSCoordinateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Care Hotline (Malaysia).
        /// </summary>
        internal static string HotlineCare {
            get {
                return ResourceManager.GetString("HotlineCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM Name.
        /// </summary>
        internal static string ImName {
            get {
                return ResourceManager.GetString("ImName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM Staff No/ IC No/Phone No.
        /// </summary>
        internal static string ImStaffIcPhone {
            get {
                return ResourceManager.GetString("ImStaffIcPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Attachments.
        /// </summary>
        internal static string IncludeAttachments {
            get {
                return ResourceManager.GetString("IncludeAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        internal static string InprogressWorkorder {
            get {
                return ResourceManager.GetString("InprogressWorkorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input CB Number.
        /// </summary>
        internal static string InputCBNumber {
            get {
                return ResourceManager.GetString("InputCBNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue By : .
        /// </summary>
        internal static string Issueby {
            get {
                return ResourceManager.GetString("Issueby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Status Date : .
        /// </summary>
        internal static string IssueStatusDate {
            get {
                return ResourceManager.GetString("IssueStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue To : .
        /// </summary>
        internal static string Issueto {
            get {
                return ResourceManager.GetString("Issueto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reading : .
        /// </summary>
        internal static string LastReading {
            get {
                return ResourceManager.GetString("LastReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reading Date : .
        /// </summary>
        internal static string LastReadingDate {
            get {
                return ResourceManager.GetString("LastReadingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location : .
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Part.
        /// </summary>
        internal static string Manufacturepart {
            get {
                return ResourceManager.GetString("Manufacturepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Country.
        /// </summary>
        internal static string Manufacturingcountry {
            get {
                return ResourceManager.GetString("Manufacturingcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Date.
        /// </summary>
        internal static string ManufacturingDate {
            get {
                return ResourceManager.GetString("ManufacturingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARK ALL AS READ.
        /// </summary>
        internal static string MarkAll {
            get {
                return ResourceManager.GetString("MarkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Details .
        /// </summary>
        internal static string MeterDetails {
            get {
                return ResourceManager.GetString("MeterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Name : .
        /// </summary>
        internal static string MeterName {
            get {
                return ResourceManager.GetString("MeterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Specific List .
        /// </summary>
        internal static string MeterSpecificList {
            get {
                return ResourceManager.GetString("MeterSpecificList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Specific to Meter Group .
        /// </summary>
        internal static string MeterSpecificToMeterGroup {
            get {
                return ResourceManager.GetString("MeterSpecificToMeterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type : .
        /// </summary>
        internal static string MeterType {
            get {
                return ResourceManager.GetString("MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Workorders.
        /// </summary>
        internal static string NewestWorkorders {
            get {
                return ResourceManager.GetString("NewestWorkorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reading : .
        /// </summary>
        internal static string NewReading {
            get {
                return ResourceManager.GetString("NewReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reading Date : .
        /// </summary>
        internal static string NewReadingDate {
            get {
                return ResourceManager.GetString("NewReadingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SQA Status.
        /// </summary>
        internal static string NewSqaStatus {
            get {
                return ResourceManager.GetString("NewSqaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status : .
        /// </summary>
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status .
        /// </summary>
        internal static string NewStatusHere {
            get {
                return ResourceManager.GetString("NewStatusHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no Attachment available..
        /// </summary>
        internal static string NoAttachmentCreated {
            get {
                return ResourceManager.GetString("NoAttachmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no Child Order created yet..
        /// </summary>
        internal static string NoChildCreated {
            get {
                return ResourceManager.GetString("NoChildCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO INTERNET.
        /// </summary>
        internal static string NOINTERNET {
            get {
                return ResourceManager.GetString("NOINTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no Testing Meter created yet..
        /// </summary>
        internal static string NoMeterCreated {
            get {
                return ResourceManager.GetString("NoMeterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Rotating Item.
        /// </summary>
        internal static string NonRotatingItem {
            get {
                return ResourceManager.GetString("NonRotatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no Permit created yet..
        /// </summary>
        internal static string NoPermitCreated {
            get {
                return ResourceManager.GetString("NoPermitCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no SQA Form created yet..
        /// </summary>
        internal static string NoSqaCreated {
            get {
                return ResourceManager.GetString("NoSqaCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops Sorry! There is still no Worklog created yet..
        /// </summary>
        internal static string NoWorklogCreated {
            get {
                return ResourceManager.GetString("NoWorklogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        internal static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass ?.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass With Condition ?.
        /// </summary>
        internal static string PassWithCondition {
            get {
                return ResourceManager.GetString("PassWithCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage :.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Attachment.
        /// </summary>
        internal static string PermitAttachment {
            get {
                return ResourceManager.GetString("PermitAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Details.
        /// </summary>
        internal static string PermitDetail {
            get {
                return ResourceManager.GetString("PermitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Type : .
        /// </summary>
        internal static string Permittype {
            get {
                return ResourceManager.GetString("Permittype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Protective Equipment?.
        /// </summary>
        internal static string PersonalProtectiveEquipment {
            get {
                return ResourceManager.GetString("PersonalProtectiveEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Your Color.
        /// </summary>
        internal static string Pickyourcolor {
            get {
                return ResourceManager.GetString("Pickyourcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Your Themes.
        /// </summary>
        internal static string Pickyourtheme {
            get {
                return ResourceManager.GetString("Pickyourtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter.
        /// </summary>
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Description.
        /// </summary>
        internal static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By : .
        /// </summary>
        internal static string Preparedby {
            get {
                return ResourceManager.GetString("Preparedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By - Comments : .
        /// </summary>
        internal static string PreparedComment {
            get {
                return ResourceManager.GetString("PreparedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Date : .
        /// </summary>
        internal static string Prepareddate {
            get {
                return ResourceManager.GetString("Prepareddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Policy.
        /// </summary>
        internal static string Privacyandpolicy {
            get {
                return ResourceManager.GetString("Privacyandpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID : .
        /// </summary>
        internal static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Phase : .
        /// </summary>
        internal static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI Checklist.
        /// </summary>
        internal static string PSIChecklist {
            get {
                return ResourceManager.GetString("PSIChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        internal static string Receivedby {
            get {
                return ResourceManager.GetString("Receivedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Statistic.
        /// </summary>
        internal static string RecordStatistic {
            get {
                return ResourceManager.GetString("RecordStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks :.
        /// </summary>
        internal static string Remarks_ {
            get {
                return ResourceManager.GetString("Remarks:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response : .
        /// </summary>
        internal static string Response_ {
            get {
                return ResourceManager.GetString("Response:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result : .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake.
        /// </summary>
        internal static string Retake {
            get {
                return ResourceManager.GetString("Retake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Form and Quality Assurance SQA.
        /// </summary>
        internal static string SafetyFormQualityAssurance {
            get {
                return ResourceManager.GetString("SafetyFormQualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety and Scope of Work Briefing?.
        /// </summary>
        internal static string SafetynScopework {
            get {
                return ResourceManager.GetString("SafetynScopework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Behavior.
        /// </summary>
        internal static string SavedBehavior {
            get {
                return ResourceManager.GetString("SavedBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Device .
        /// </summary>
        internal static string Savetodevice {
            get {
                return ResourceManager.GetString("Savetodevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope of Work.
        /// </summary>
        internal static string Scopeofwork {
            get {
                return ResourceManager.GetString("Scopeofwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Work Order.
        /// </summary>
        internal static string SearchWorkorder {
            get {
                return ResourceManager.GetString("SearchWorkorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification, copying, reproduction, republication, uploading, posting, transmission or distribution in any manner of the said information on the website, including text, graphics, code and/or software without permission in writing is prohibited.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT YOUR PREFERRED LANGUAGE.
        /// </summary>
        internal static string SelectPreferredLanguage {
            get {
                return ResourceManager.GetString("SelectPreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign By Contractor.
        /// </summary>
        internal static string SignByContractor {
            get {
                return ResourceManager.GetString("SignByContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign By TNB?.
        /// </summary>
        internal static string SignByTNB {
            get {
                return ResourceManager.GetString("SignByTNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Sortby {
            get {
                return ResourceManager.GetString("Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQA Attachmets.
        /// </summary>
        internal static string SQAAttachmets {
            get {
                return ResourceManager.GetString("SQAAttachmets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQA/SQE Checklist.
        /// </summary>
        internal static string SQAChecklist {
            get {
                return ResourceManager.GetString("SQAChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQA/SQE Form Page.
        /// </summary>
        internal static string SQAFormPage {
            get {
                return ResourceManager.GetString("SQAFormPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQA Status .
        /// </summary>
        internal static string SQAStatus {
            get {
                return ResourceManager.GetString("SQAStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff No/ IC No/Phone No.
        /// </summary>
        internal static string StaffIcPhone {
            get {
                return ResourceManager.GetString("StaffIcPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State : .
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station : .
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Date : .
        /// </summary>
        internal static string StatusDate {
            get {
                return ResourceManager.GetString("StatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Description :.
        /// </summary>
        internal static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Station : .
        /// </summary>
        internal static string SubStation {
            get {
                return ResourceManager.GetString("SubStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subvertical.
        /// </summary>
        internal static string Subvertical {
            get {
                return ResourceManager.GetString("Subvertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Vertical : .
        /// </summary>
        internal static string Subvertical_ {
            get {
                return ResourceManager.GetString("Subvertical:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subzone : .
        /// </summary>
        internal static string Subzone {
            get {
                return ResourceManager.GetString("Subzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORT.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNB Disclaimer.
        /// </summary>
        internal static string Termofservice {
            get {
                return ResourceManager.GetString("Termofservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Form Page.
        /// </summary>
        internal static string Testformpage {
            get {
                return ResourceManager.GetString("Testformpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        internal static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE NOW ENTERING TNB&apos;S PROPERTY!.
        /// </summary>
        internal static string TnbDisclaimer {
            get {
                return ResourceManager.GetString("TnbDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Percentage.
        /// </summary>
        internal static string TotalPercentage_ {
            get {
                return ResourceManager.GetString("TotalPercentage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score :.
        /// </summary>
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score .
        /// </summary>
        internal static string TotalScore_ {
            get {
                return ResourceManager.GetString("TotalScore:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalWorkorder {
            get {
                return ResourceManager.GetString("TotalWorkorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Fund : .
        /// </summary>
        internal static string Trustfund {
            get {
                return ResourceManager.GetString("Trustfund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY AGAIN!.
        /// </summary>
        internal static string TRYAGAIN {
            get {
                return ResourceManager.GetString("TRYAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Charts.
        /// </summary>
        internal static string TypeChart {
            get {
                return ResourceManager.GetString("TypeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Here.
        /// </summary>
        internal static string TypeHere {
            get {
                return ResourceManager.GetString("TypeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Behavior.
        /// </summary>
        internal static string UnsavedBehavior {
            get {
                return ResourceManager.GetString("UnsavedBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsecured Behavior Scoring.
        /// </summary>
        internal static string UnsecuredBehaviorScoring {
            get {
                return ResourceManager.GetString("UnsecuredBehaviorScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated By : .
        /// </summary>
        internal static string Validatedby {
            get {
                return ResourceManager.GetString("Validatedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated By - Comments : .
        /// </summary>
        internal static string ValidatedComment {
            get {
                return ResourceManager.GetString("ValidatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated Date : .
        /// </summary>
        internal static string Validateddate {
            get {
                return ResourceManager.GetString("Validateddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value : .
        /// </summary>
        internal static string Value_ {
            get {
                return ResourceManager.GetString("Value:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical : .
        /// </summary>
        internal static string Vertical_ {
            get {
                return ResourceManager.GetString("Vertical:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by : .
        /// </summary>
        internal static string ViewBy {
            get {
                return ResourceManager.GetString("ViewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart by : .
        /// </summary>
        internal static string Viewchartby {
            get {
                return ResourceManager.GetString("Viewchartby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Level : .
        /// </summary>
        internal static string VoltageLevel {
            get {
                return ResourceManager.GetString("VoltageLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBS Element : .
        /// </summary>
        internal static string WBSElement {
            get {
                return ResourceManager.GetString("WBSElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Attachments.
        /// </summary>
        internal static string WithoutAttachments {
            get {
                return ResourceManager.GetString("WithoutAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Number.
        /// </summary>
        internal static string Wonumber {
            get {
                return ResourceManager.GetString("Wonumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklog.
        /// </summary>
        internal static string Worklog {
            get {
                return ResourceManager.GetString("Worklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklog Details.
        /// </summary>
        internal static string WorklogDetails {
            get {
                return ResourceManager.GetString("WorklogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workorder.
        /// </summary>
        internal static string Workorder {
            get {
                return ResourceManager.GetString("Workorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Details .
        /// </summary>
        internal static string WorkorderDetail {
            get {
                return ResourceManager.GetString("WorkorderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workorder Map.
        /// </summary>
        internal static string WorkorderMap {
            get {
                return ResourceManager.GetString("WorkorderMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workorder Number : .
        /// </summary>
        internal static string WorkorderNumber {
            get {
                return ResourceManager.GetString("WorkorderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workorder Sync.
        /// </summary>
        internal static string WorkorderSync {
            get {
                return ResourceManager.GetString("WorkorderSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Scope.
        /// </summary>
        internal static string Workscope {
            get {
                return ResourceManager.GetString("Workscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Scope : .
        /// </summary>
        internal static string Workscope_ {
            get {
                return ResourceManager.GetString("Workscope:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type.
        /// </summary>
        internal static string Worktype {
            get {
                return ResourceManager.GetString("Worktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type : .
        /// </summary>
        internal static string Worktype_ {
            get {
                return ResourceManager.GetString("Worktype:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO Status.
        /// </summary>
        internal static string WOStatus {
            get {
                return ResourceManager.GetString("WOStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO Type.
        /// </summary>
        internal static string WOType {
            get {
                return ResourceManager.GetString("WOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to the internet to complete this action!.
        /// </summary>
        internal static string YOU {
            get {
                return ResourceManager.GetString("YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone : .
        /// </summary>
        internal static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
