//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcms {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ms {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ms() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mcms.AppResources.ms", typeof(AppResources_ms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        internal static string AddSignature
        {
            get
            {
                return ResourceManager.GetString("AddSignature", resourceCulture);
            }
        }
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string Approvedby {
            get {
                return ResourceManager.GetString("Approvedby", resourceCulture);
            }
        }
        
        internal static string Approvedby_ {
            get {
                return ResourceManager.GetString("Approvedby:", resourceCulture);
            }
        }
        
        internal static string ApprovedComment {
            get {
                return ResourceManager.GetString("ApprovedComment", resourceCulture);
            }
        }
        
        internal static string Approveddate {
            get {
                return ResourceManager.GetString("Approveddate", resourceCulture);
            }
        }
        
        internal static string Approveddate_ {
            get {
                return ResourceManager.GetString("Approveddate:", resourceCulture);
            }
        }
        
        internal static string ApprovedWorkorder {
            get {
                return ResourceManager.GetString("ApprovedWorkorder", resourceCulture);
            }
        }
        
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }

        internal static string AssetCondition
        {
            get
            {
                return ResourceManager.GetString("AssetCondition", resourceCulture);
            }
        }

        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        internal static string Attachment_ {
            get {
                return ResourceManager.GetString("Attachment:", resourceCulture);
            }
        }
        
        internal static string AttachmentDetail {
            get {
                return ResourceManager.GetString("AttachmentDetail", resourceCulture);
            }
        }
        
        internal static string AttachmentForm {
            get {
                return ResourceManager.GetString("AttachmentForm", resourceCulture);
            }
        }
        
        internal static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        internal static string AuditNo {
            get {
                return ResourceManager.GetString("AuditNo", resourceCulture);
            }
        }
        internal static string AuthorizedPerson
        {
            get
            {
                return ResourceManager.GetString("AuthorizedPerson", resourceCulture);
            }
        }
        internal static string BankDraft {
            get {
                return ResourceManager.GetString("BankDraft", resourceCulture);
            }
        }
        
        internal static string BankGuarantee {
            get {
                return ResourceManager.GetString("BankGuarantee", resourceCulture);
            }
        }
        
        internal static string Businessarea {
            get {
                return ResourceManager.GetString("Businessarea", resourceCulture);
            }
        }

        internal static string Brand
        {
            get
            {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }

        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        internal static string ChangeSQAStatus {
            get {
                return ResourceManager.GetString("ChangeSQAStatus", resourceCulture);
            }
        }
        
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        internal static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        internal static string ChecklistForm {
            get {
                return ResourceManager.GetString("ChecklistForm", resourceCulture);
            }
        }
        internal static string ChecklistType
        {
            get
            {
                return ResourceManager.GetString("ChecklistType", resourceCulture);
            }
        }
        internal static string ChildWorkorders {
            get {
                return ResourceManager.GetString("ChildWorkorders", resourceCulture);
            }
        }
        
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        internal static string ClicktoDownload
        {
            get
            {
                return ResourceManager.GetString("ClicktoDownload", resourceCulture);
            }
        }
        internal static string Comments
        {
            get
            {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        internal static string CompetentPerson
        {
            get
            {
                return ResourceManager.GetString("CompetentPerson", resourceCulture);
            }
        }
        internal static string CompanyDepartment
        {
            get
            {
                return ResourceManager.GetString("CompanyDepartment", resourceCulture);
            }
        }
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        internal static string ContractorName {
            get {
                return ResourceManager.GetString("ContractorName", resourceCulture);
            }
        }
        internal static string Correctionnote{
            get{
                return ResourceManager.GetString("Correctionnote", resourceCulture);
            }
        }
        internal static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        internal static string Createddate {
            get {
                return ResourceManager.GetString("Createddate", resourceCulture);
            }
        }
        internal static string DataLookup
        {
            get
            {
                return ResourceManager.GetString("DataLookup", resourceCulture);
            }
        }
        internal static string DefectDescription_ {
            get {
                return ResourceManager.GetString("DefectDescription:", resourceCulture);
            }
        }
        
        internal static string DefectRecifiedDate_ {
            get {
                return ResourceManager.GetString("DefectRecifiedDate:", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        internal static string DeliveryDate
        {
            get
            {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }

        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        internal static string DigitalSignature
        {
            get
            {
                return ResourceManager.GetString("DigitalSignature", resourceCulture);
            }
        }
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        internal static string Discovery
        {
            get
            {
                return ResourceManager.GetString("Discovery", resourceCulture);
            }
        }
        internal static string DownloadMaster {
            get {
                return ResourceManager.GetString("DownloadMaster", resourceCulture);
            }
        }
        
        internal static string EnterNewReading {
            get {
                return ResourceManager.GetString("EnterNewReading", resourceCulture);
            }
        }
        
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        internal static string Favourite
        {
            get
            {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }

        internal static string Filterby {
            get {
                return ResourceManager.GetString("Filterby", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        internal static string ForanyenquirieS
        {
            get
            {
                return ResourceManager.GetString("ForanyenquirieS", resourceCulture);
            }
        }
        internal static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        internal static string GetGPS {
            get {
                return ResourceManager.GetString("GetGPS", resourceCulture);
            }
        }
        
        internal static string GPSCoordinate {
            get {
                return ResourceManager.GetString("GPSCoordinate", resourceCulture);
            }
        }
        
        internal static string GPSCoordinateNew {
            get {
                return ResourceManager.GetString("GPSCoordinateNew", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        internal static string HotlineCare
        {
            get
            {
                return ResourceManager.GetString("HotlineCare", resourceCulture);
            }
        }
        internal static string ImName {
            get {
                return ResourceManager.GetString("ImName", resourceCulture);
            }
        }
        
        internal static string ImStaffIcPhone {
            get {
                return ResourceManager.GetString("ImStaffIcPhone", resourceCulture);
            }
        }
        internal static string IncludeAttachments
        {
            get
            {
                return ResourceManager.GetString("IncludeAttachments", resourceCulture);
            }
        }
        internal static string InprogressWorkorder {
            get {
                return ResourceManager.GetString("InprogressWorkorder", resourceCulture);
            }
        }
        
        internal static string InputCBNumber {
            get {
                return ResourceManager.GetString("InputCBNumber", resourceCulture);
            }
        }
        
        internal static string Issueby {
            get {
                return ResourceManager.GetString("Issueby", resourceCulture);
            }
        }
        
        internal static string IssueStatusDate {
            get {
                return ResourceManager.GetString("IssueStatusDate", resourceCulture);
            }
        }
        
        internal static string Issueto {
            get {
                return ResourceManager.GetString("Issueto", resourceCulture);
            }
        }
        
        internal static string LastReading {
            get {
                return ResourceManager.GetString("LastReading", resourceCulture);
            }
        }
        
        internal static string LastReadingDate {
            get {
                return ResourceManager.GetString("LastReadingDate", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        internal static string Manufacturer{
            get{
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        internal static string Manufacturingcountry{
            get{
                return ResourceManager.GetString("Manufacturingcountry", resourceCulture);
            }
        }
        internal static string ManufacturingDate
        {
            get
            {
                return ResourceManager.GetString("ManufacturingDate", resourceCulture);
            }
        }
        internal static string Manufacturepart{
            get
            {
                return ResourceManager.GetString("Manufacturepart", resourceCulture);
            }
        }
        internal static string MarkAll {
            get {
                return ResourceManager.GetString("MarkAll", resourceCulture);
            }
        }
        
        internal static string MeterDetails {
            get {
                return ResourceManager.GetString("MeterDetails", resourceCulture);
            }
        }
        
        internal static string MeterName {
            get {
                return ResourceManager.GetString("MeterName", resourceCulture);
            }
        }
        
        internal static string MeterSpecificList {
            get {
                return ResourceManager.GetString("MeterSpecificList", resourceCulture);
            }
        }
        
        internal static string MeterSpecificToMeterGroup {
            get {
                return ResourceManager.GetString("MeterSpecificToMeterGroup", resourceCulture);
            }
        }
        internal static string MeterType
        {
            get
            {
                return ResourceManager.GetString("MeterType", resourceCulture);
            }
        }
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        internal static string NewestWorkorders {
            get {
                return ResourceManager.GetString("NewestWorkorders", resourceCulture);
            }
        }
        
        internal static string NewReading {
            get {
                return ResourceManager.GetString("NewReading", resourceCulture);
            }
        }
        
        internal static string NewReadingDate {
            get {
                return ResourceManager.GetString("NewReadingDate", resourceCulture);
            }
        }
        
        internal static string NewSqaStatus {
            get {
                return ResourceManager.GetString("NewSqaStatus", resourceCulture);
            }
        }
        
        internal static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        internal static string NewStatusHere {
            get {
                return ResourceManager.GetString("NewStatusHere", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NoAttachmentCreated {
            get {
                return ResourceManager.GetString("NoAttachmentCreated", resourceCulture);
            }
        }
        
        internal static string NoChildCreated {
            get {
                return ResourceManager.GetString("NoChildCreated", resourceCulture);
            }
        }
        internal static string NOINTERNET
        {
            get
            {
                return ResourceManager.GetString("NOINTERNET", resourceCulture);
            }
        }
        internal static string NoMeterCreated {
            get {
                return ResourceManager.GetString("NoMeterCreated", resourceCulture);
            }
        }

        internal static string NonRotatingItem{
            get{
                return ResourceManager.GetString("NonRotatingItem", resourceCulture);
            }
        }

        internal static string NoPermitCreated {
            get {
                return ResourceManager.GetString("NoPermitCreated", resourceCulture);
            }
        }
        
        internal static string NoSqaCreated {
            get {
                return ResourceManager.GetString("NoSqaCreated", resourceCulture);
            }
        }
        
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string NoWorklogCreated {
            get {
                return ResourceManager.GetString("NoWorklogCreated", resourceCulture);
            }
        }
        
        internal static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        internal static string PassWithCondition {
            get {
                return ResourceManager.GetString("PassWithCondition", resourceCulture);
            }
        }
        
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        internal static string PermitAttachment {
            get {
                return ResourceManager.GetString("PermitAttachment", resourceCulture);
            }
        }
        
        internal static string PermitDetail {
            get {
                return ResourceManager.GetString("PermitDetail", resourceCulture);
            }
        }
        
        internal static string Permittype {
            get {
                return ResourceManager.GetString("Permittype", resourceCulture);
            }
        }
        
        internal static string PersonalProtectiveEquipment {
            get {
                return ResourceManager.GetString("PersonalProtectiveEquipment", resourceCulture);
            }
        }
        internal static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        internal static string Pickyourcolor {
            get {
                return ResourceManager.GetString("Pickyourcolor", resourceCulture);
            }
        }
        
        internal static string Pickyourtheme {
            get {
                return ResourceManager.GetString("Pickyourtheme", resourceCulture);
            }
        }
        
        internal static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        internal static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        internal static string Preparedby {
            get {
                return ResourceManager.GetString("Preparedby", resourceCulture);
            }
        }
        
        internal static string PreparedComment {
            get {
                return ResourceManager.GetString("PreparedComment", resourceCulture);
            }
        }
        
        internal static string Prepareddate {
            get {
                return ResourceManager.GetString("Prepareddate", resourceCulture);
            }
        }
        
        internal static string Privacyandpolicy {
            get {
                return ResourceManager.GetString("Privacyandpolicy", resourceCulture);
            }
        }
        
        internal static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        internal static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        internal static string PSIChecklist
        {
            get
            {
                return ResourceManager.GetString("PSIChecklist", resourceCulture);
            }
        }
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        internal static string Receivedby {
            get {
                return ResourceManager.GetString("Receivedby", resourceCulture);
            }
        }
        
        internal static string RecordStatistic {
            get {
                return ResourceManager.GetString("RecordStatistic", resourceCulture);
            }
        }
        
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        internal static string Remarks_ {
            get {
                return ResourceManager.GetString("Remarks:", resourceCulture);
            }
        }
        
        internal static string Response_ {
            get {
                return ResourceManager.GetString("Response:", resourceCulture);
            }
        }
        
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        internal static string Retake {
            get {
                return ResourceManager.GetString("Retake", resourceCulture);
            }
        }
        
        internal static string SafetyFormQualityAssurance {
            get {
                return ResourceManager.GetString("SafetyFormQualityAssurance", resourceCulture);
            }
        }
        
        internal static string SafetynScopework {
            get {
                return ResourceManager.GetString("SafetynScopework", resourceCulture);
            }
        }

        internal static string Savetodevice{
            get{
                return ResourceManager.GetString("Savetodevice", resourceCulture);
            }
        }

        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        internal static string SavedBehavior {
            get {
                return ResourceManager.GetString("SavedBehavior", resourceCulture);
            }
        }
        
        internal static string Scopeofwork {
            get {
                return ResourceManager.GetString("Scopeofwork", resourceCulture);
            }
        }
        
        internal static string SearchWorkorder {
            get {
                return ResourceManager.GetString("SearchWorkorder", resourceCulture);
            }
        }
        
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        internal static string SelectPreferredLanguage {
            get {
                return ResourceManager.GetString("SelectPreferredLanguage", resourceCulture);
            }
        }
        
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        internal static string Sortby {
            get {
                return ResourceManager.GetString("Sortby", resourceCulture);
            }
        }
        internal static string Signature
        {
            get
            {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        internal static string SignByTNB
        {
            get
            {
                return ResourceManager.GetString("SignByTNB", resourceCulture);
            }
        }
        internal static string SignByContractor
        {
            get
            {
                return ResourceManager.GetString("SignByContractor", resourceCulture);
            }
        }
        internal static string SQAAttachmets
        {
            get
            {
                return ResourceManager.GetString("SQAAttachmets", resourceCulture);
            }
        }
        internal static string SQAChecklist {
            get {
                return ResourceManager.GetString("SQAChecklist", resourceCulture);
            }
        }
        
        internal static string SQAFormPage {
            get {
                return ResourceManager.GetString("SQAFormPage", resourceCulture);
            }
        }
        
        internal static string SQAStatus {
            get {
                return ResourceManager.GetString("SQAStatus", resourceCulture);
            }
        }
        
        internal static string StaffIcPhone {
            get {
                return ResourceManager.GetString("StaffIcPhone", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        internal static string StatusDate {
            get {
                return ResourceManager.GetString("StatusDate", resourceCulture);
            }
        }
        internal static string StatusDescription
        {
            get
            {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        internal static string SubStation {
            get {
                return ResourceManager.GetString("SubStation", resourceCulture);
            }
        }
        
        internal static string Subvertical {
            get {
                return ResourceManager.GetString("Subvertical", resourceCulture);
            }
        }
        
        internal static string Subvertical_ {
            get {
                return ResourceManager.GetString("Subvertical:", resourceCulture);
            }
        }
        
        internal static string Subzone {
            get {
                return ResourceManager.GetString("Subzone", resourceCulture);
            }
        }
        internal static string Summary
        {
            get
            {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        internal static string Termofservice {
            get {
                return ResourceManager.GetString("Termofservice", resourceCulture);
            }
        }
        
        internal static string Testformpage {
            get {
                return ResourceManager.GetString("Testformpage", resourceCulture);
            }
        }
        
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        internal static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string TnbDisclaimer {
            get {
                return ResourceManager.GetString("TnbDisclaimer", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string TotalPercentage_ {
            get {
                return ResourceManager.GetString("TotalPercentage:", resourceCulture);
            }
        }
        
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        internal static string TotalScore_ {
            get {
                return ResourceManager.GetString("TotalScore:", resourceCulture);
            }
        }
        
        internal static string TotalWorkorder {
            get {
                return ResourceManager.GetString("TotalWorkorder", resourceCulture);
            }
        }
        
        internal static string Trustfund {
            get {
                return ResourceManager.GetString("Trustfund", resourceCulture);
            }
        }
        internal static string TRYAGAIN
        {
            get
            {
                return ResourceManager.GetString("TRYAGAIN", resourceCulture);
            }
        }

        internal static string TypeChart {
            get {
                return ResourceManager.GetString("TypeChart", resourceCulture);
            }
        }
        
        internal static string TypeHere {
            get {
                return ResourceManager.GetString("TypeHere", resourceCulture);
            }
        }
        
        internal static string UnsavedBehavior {
            get {
                return ResourceManager.GetString("UnsavedBehavior", resourceCulture);
            }
        }
        
        internal static string UnsecuredBehaviorScoring {
            get {
                return ResourceManager.GetString("UnsecuredBehaviorScoring", resourceCulture);
            }
        }
        
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        internal static string Validatedby {
            get {
                return ResourceManager.GetString("Validatedby", resourceCulture);
            }
        }
        
        internal static string ValidatedComment {
            get {
                return ResourceManager.GetString("ValidatedComment", resourceCulture);
            }
        }
        
        internal static string Validateddate {
            get {
                return ResourceManager.GetString("Validateddate", resourceCulture);
            }
        }
        
        internal static string Value_ {
            get {
                return ResourceManager.GetString("Value:", resourceCulture);
            }
        }
        
        internal static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        internal static string Vertical_ {
            get {
                return ResourceManager.GetString("Vertical:", resourceCulture);
            }
        }
        
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        internal static string ViewBy {
            get {
                return ResourceManager.GetString("ViewBy", resourceCulture);
            }
        }
        
        internal static string Viewchartby {
            get {
                return ResourceManager.GetString("Viewchartby", resourceCulture);
            }
        }
        
        internal static string VoltageLevel {
            get {
                return ResourceManager.GetString("VoltageLevel", resourceCulture);
            }
        }
        
        internal static string WBSElement {
            get {
                return ResourceManager.GetString("WBSElement", resourceCulture);
            }
        }
        internal static string WithoutAttachments
        {
            get
            {
                return ResourceManager.GetString("WithoutAttachments", resourceCulture);
            }
        }
        internal static string Wonumber {
            get {
                return ResourceManager.GetString("Wonumber", resourceCulture);
            }
        }
        
        internal static string Worklog {
            get {
                return ResourceManager.GetString("Worklog", resourceCulture);
            }
        }
        internal static string WorklogDetails
        {
            get
            {
                return ResourceManager.GetString("WorklogDetails", resourceCulture);
            }
        }

        internal static string Workorder {
            get {
                return ResourceManager.GetString("Workorder", resourceCulture);
            }
        }
        
        internal static string WorkorderDetail {
            get {
                return ResourceManager.GetString("WorkorderDetail", resourceCulture);
            }
        }
        
        internal static string WorkorderMap {
            get {
                return ResourceManager.GetString("WorkorderMap", resourceCulture);
            }
        }
        
        internal static string WorkorderNumber {
            get {
                return ResourceManager.GetString("WorkorderNumber", resourceCulture);
            }
        }
        internal static string WorkorderSync
        {
            get
            {
                return ResourceManager.GetString("WorkorderSync", resourceCulture);
            }
        }

        internal static string Workscope {
            get {
                return ResourceManager.GetString("Workscope", resourceCulture);
            }
        }
        
        internal static string Workscope_ {
            get {
                return ResourceManager.GetString("Workscope:", resourceCulture);
            }
        }
        
        internal static string Worktype {
            get {
                return ResourceManager.GetString("Worktype", resourceCulture);
            }
        }
        
        internal static string Worktype_ {
            get {
                return ResourceManager.GetString("Worktype:", resourceCulture);
            }
        }
        
        internal static string WOStatus {
            get {
                return ResourceManager.GetString("WOStatus", resourceCulture);
            }
        }
        
        internal static string WOType {
            get {
                return ResourceManager.GetString("WOType", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        internal static string YOU
        {
            get
            {
                return ResourceManager.GetString("YOU", resourceCulture);
            }
        }

        internal static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
        
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
    }
}
